package com.ssafy.d3v.backend.question.entity;

public enum JobRole {
    FRONTEND,
    BACKEND,
    MOBILE,
    DATABASE,
    DEVOPS,
    PUBLISHER,
    DATA_SCIENCE,
    MACHINE_LEARNING,
    GAME_DEVELOPMENT,
    EMBEDDED,
    CYBER_SECURITY,
    AI_ENGINEERING,
    NETWORK_ENGINEERING,
    PROJECT_MANAGER,
    BLOCKCHAIN,
    TESTING,
    FULLSTACK,
}
