package com.ssafy.d3v.backend.question.domain;

public enum SkillType {
    C, C_PLUS, C_SHARP, JAVA, JAVASCRIPT, HTML, CSS, PYTHON, GO,
    NETWORK, DATABASE, ALGORITHM, DATA_STRUCTURE, OPERATING_SYSTEM,
    REACT, VUE, ANGULAR, TYPESCRIPT, SASS,
    SPRING, SPRING_BOOT, NODE_JS, EXPRESS, DJANGO, FLASK, RUBY,
    SWIFT, KOTLIN, FLUTTER, REACT_NATIVE, OBJECTIVE_C,
    MYSQL, POSTGRESQL, MONGODB, ORACLE, SQLITE, REDIS, MARIADB,
    DOCKER, KUBERNETES, AWS, AZURE, GCP, TERRAFORM, ANSIBLE, JENKINS, GITHUB_ACTION, GITLAB_RUNNER,
    R, NUMPY, PANDAS, TENSORFLOW, PYTORCH, MATPLOTLIB, SCIKIT_LEARN, HADOOP, SPARK, KERAS, MLLIB, OPENCV, NLTK,
    UNITY, UNREAL_ENGINE, GODOT, BLENDER, ASSEMBLY, MICROCONTROLLERS, RTOS, IOT,
    KALI_LINUX, WIRESHARK, METASPLOIT, BURP_SUITE, NMAP, OWASP, ENCRYPTION,
    SOLIDITY, ETHEREUM, HYPERLEDGER, WEB3_JS, TRUFFLE, GANACHE,
    JUNIT, SELENIUM, CUCUMBER, TESTNG, APPIUM, GRAPHQL, SQL
}