const dummyQuestions = [
    {
      id: 1,
      status: "solved",
      questionContent: "React의 Virtual DOM 동작 원리",
      challengeCount: 1,
      answerCount: 7,
      jobCategory: ["Frontend"],
      skills: ["React", "JavaScript"],
    },
    {
      id: 2,
      status: "unsolved",
      questionContent: "JavaScript 이벤트 루프와 비동기 처리",
      challengeCount: 2,
      answerCount: 1,
      jobCategory: ["Frontend"],
      skills: ["JavaScript"],
    },
    {
      id: 3,
      status: "unsolved",
      questionContent: "Spring Security 인증 구현 방법",
      challengeCount: 3,
      answerCount: 2,
      jobCategory: ["Backend"],
      skills: ["Spring", "Java"],
    },
    {
      id: 4,
      status: "solved",
      questionContent: "TypeScript 제네릭 활용법",
      challengeCount: 4,
      answerCount: 0,
      jobCategory: ["Frontend"],
      skills: ["TypeScript"],
    },
    {
      id: 5,
      status: "unsolved",
      questionContent: "Docker 컨테이너 네트워킹",
      challengeCount: 5,
      answerCount: 1,
      jobCategory: ["DevOps"],
      skills: ["Docker"],
    },
    {
      id: 6,
      status: "solved",
      questionContent: "React Native 성능 최적화",
      challengeCount: 6,
      answerCount: 2,
      jobCategory: ["Mobile"],
      skills: ["React Native"],
    },
    {
      id: 7,
      status: "unsolved",
      questionContent: "Node.js 메모리 누수 디버깅",
      challengeCount: 7,
      answerCount: 3,
      jobCategory: ["Backend"],
      skills: ["Node.js"],
    },
    {
      id: 8,
      status: "solved",
      questionContent: "Vue.js 상태 관리 패턴",
      challengeCount: 2,
      answerCount: 0,
      jobCategory: ["Frontend"],
      skills: ["Vue"],
    },
    {
      id: 9,
      status: "unsolved",
      questionContent: "Kubernetes 파드 스케줄링",
      challengeCount: 3,
      answerCount: 4,
      jobCategory: ["DevOps"],
      skills: ["Kubernetes"],
    },
    {
      id: 10,
      status: "solved",
      questionContent: "Flutter 위젯 라이프사이클",
      challengeCount: 5,
      answerCount: 5,
      jobCategory: ["Mobile"],
      skills: ["Flutter"],
    },
    {
      id: 11,
      status: "unsolved",
      questionContent: "Django REST framework 인증",
      challengeCount: 1,
      answerCount: 0,
      jobCategory: ["Backend"],
      skills: ["Django", "Python"],
    },
    {
      id: 12,
      status: "solved",
      questionContent: "Angular 의존성 주입",
      challengeCount: 3,
      answerCount: 3,
      jobCategory: ["Frontend"],
      skills: ["Angular"],
    },
    {
      id: 13,
      status: "unsolved",
      questionContent: "iOS 앱 배포 프로세스",
      challengeCount: 2,
      answerCount: 1,
      jobCategory: ["Mobile"],
      skills: ["iOS"],
    },
    {
      id: 14,
      status: "solved",
      questionContent: "AWS Lambda 함수 최적화",
      challengeCount: 6,
      answerCount: 1,
      jobCategory: ["DevOps"],
      skills: ["AWS"],
    },
    {
      id: 15,
      status: "unsolved",
      questionContent: "Spring Boot JPA 성능 튜닝",
      challengeCount: 4,
      answerCount: 4,
      jobCategory: ["Backend"],
      skills: ["Spring", "Java"],
    },
    {
      id: 16,
      status: "solved",
      questionContent: "React Query 캐시 전략",
      challengeCount: 5,
      answerCount: 0,
      jobCategory: ["Frontend"],
      skills: ["React"],
    },
    {
      id: 17,
      status: "unsolved",
      questionContent: "Jenkins 파이프라인 구축",
      challengeCount: 2,
      answerCount: 2,
      jobCategory: ["DevOps"],
      skills: ["Jenkins"],
    },
    {
      id: 18,
      status: "solved",
      questionContent: "Android 백그라운드 처리",
      challengeCount: 1,
      answerCount: 6,
      jobCategory: ["Mobile"],
      skills: ["Android"],
    },
    {
      id: 19,
      status: "unsolved",
      questionContent: "TypeScript 타입 추론",
      challengeCount: 3,
      answerCount: 1,
      jobCategory: ["Frontend"],
      skills: ["TypeScript"],
    },
    {
      id: 20,
      status: "solved",
      questionContent: "Python FastAPI 비동기 처리",
      challengeCount: 4,
      answerCount: 2,
      jobCategory: ["Backend"],
      skills: ["Python"],
    },
    {
      id: 21,
      status: "unsolved",
      questionContent: "Docker Compose 구성",
      challengeCount: 1,
      answerCount: 5,
      jobCategory: ["DevOps"],
      skills: ["Docker"],
    },
    {
      id: 22,
      status: "solved",
      questionContent: "React Native 네비게이션",
      challengeCount: 7,
      answerCount: 4,
      jobCategory: ["Mobile"],
      skills: ["React Native"],
    },
    {
      id: 23,
      status: "unsolved",
      questionContent: "Node.js 마이크로서비스",
      challengeCount: 2,
      answerCount: 3,
      jobCategory: ["Backend"],
      skills: ["Node.js"],
    },
    {
      id: 24,
      status: "solved",
      questionContent: "Vue.js 컴포지션 API",
      challengeCount: 6,
      answerCount: 0,
      jobCategory: ["Frontend"],
      skills: ["Vue"],
    },
    {
      id: 25,
      status: "unsolved",
      questionContent: "AWS ECS 클러스터 관리",
      challengeCount: 5,
      answerCount: 2,
      jobCategory: ["DevOps"],
      skills: ["AWS"],
    },
    {
      id: 26,
      status: "solved",
      questionContent: "Flutter 상태 관리",
      challengeCount: 1,
      answerCount: 0,
      jobCategory: ["Mobile"],
      skills: ["Flutter"],
    },
    {
      id: 27,
      status: "unsolved",
      questionContent: "Spring WebFlux 리액티브",
      challengeCount: 3,
      answerCount: 1,
      jobCategory: ["Backend"],
      skills: ["Spring", "Java"],
    },
    {
      id: 28,
      status: "solved",
      questionContent: "Angular 변화 감지",
      challengeCount: 2,
      answerCount: 2,
      jobCategory: ["Frontend"],
      skills: ["Angular"],
    },
    {
      id: 29,
      status: "unsolved",
      questionContent: "iOS 푸시 알림 구현",
      challengeCount: 4,
      answerCount: 0,
      jobCategory: ["Mobile"],
      skills: ["iOS"],
    },
    {
      id: 30,
      status: "solved",
      questionContent: "Kubernetes 볼륨 관리",
      challengeCount: 6,
      answerCount: 3,
      jobCategory: ["DevOps"],
      skills: ["Kubernetes"],
    },
    {
      id: 31,
      status: "solved",
      questionContent: "Django 캐시 전략",
      challengeCount: 6,
      answerCount: 3,
      jobCategory: ["Backend"],
      skills: ["Django", "Python"],
    },
    {
      id: 32,
      status: "unsolved",
      questionContent: "Python과 R을 활용한 데이터 분석 기법 비교",
      challengeCount: 2,
      answerCount: 1,
      jobCategory: ["Backend", "Data Science"],
      skills: ["Python", "R", "Pandas"],
    },
    {
      id: 33,
      status: "solved",
      questionContent: "Terraform을 활용한 클라우드 인프라 코드 관리",
      challengeCount: 3,
      answerCount: 2,
      jobCategory: ["DevOps"],
      skills: ["Terraform", "AWS"],
    },
    {
      id: 34,
      status: "unsolved",
      questionContent: "React와 Vue.js의 상태 관리 비교",
      challengeCount: 5,
      answerCount: 0,
      jobCategory: ["Frontend"],
      skills: ["React", "Vue", "JavaScript"],
    },
    {
      id: 35,
      status: "solved",
      questionContent: "Java로 대용량 트랜잭션 처리 구현",
      challengeCount: 4,
      answerCount: 4,
      jobCategory: ["Backend"],
      skills: ["Java", "Spring"],
    },
    {
      id: 36,
      status: "unsolved",
      questionContent: "Docker Swarm과 Kubernetes 비교",
      challengeCount: 6,
      answerCount: 1,
      jobCategory: ["DevOps"],
      skills: ["Docker", "Kubernetes"],
    },
    {
      id: 37,
      status: "solved",
      questionContent: "iOS와 Android에서 푸시 알림 동작 비교",
      challengeCount: 2,
      answerCount: 3,
      jobCategory: ["Mobile"],
      skills: ["iOS", "Android", "Push Notifications"],
    },
    {
      id: 38,
      status: "unsolved",
      questionContent: "Django ORM 최적화 전략",
      challengeCount: 3,
      answerCount: 2,
      jobCategory: ["Backend", "Data Science"],
      skills: ["Django", "Python", "SQL"],
    },
    {
      id: 39,
      status: "solved",
      questionContent: "Angular와 React의 성능 최적화 전략",
      challengeCount: 7,
      answerCount: 2,
      jobCategory: ["Frontend"],
      skills: ["Angular", "React", "JavaScript"],
    },
    {
      id: 40,
      status: "unsolved",
      questionContent: "Azure와 AWS 클라우드 비교",
      challengeCount: 5,
      answerCount: 0,
      jobCategory: ["DevOps"],
      skills: ["AWS", "Azure", "Cloud Computing"],
    },
    {
      id: 41,
      status: "solved",
      questionContent: "Flutter로 멀티플랫폼 앱 개발",
      challengeCount: 6,
      answerCount: 5,
      jobCategory: ["Mobile"],
      skills: ["Flutter", "Dart"],
    },
    {
      id: 42,
      status: "unsolved",
      questionContent: "Kafka를 활용한 실시간 데이터 처리",
      challengeCount: 4,
      answerCount: 2,
      jobCategory: ["Database", "Backend"],
      skills: ["Kafka", "Spark", "Java"],
    },
    {
      id: 43,
      status: "solved",
      questionContent: "CI/CD 파이프라인 구축 사례",
      challengeCount: 5,
      answerCount: 4,
      jobCategory: ["DevOps", "Backend"],
      skills: ["Jenkins", "Git", "Docker"],
    },
    {
      id: 44,
      status: "unsolved",
      questionContent: "머신러닝 모델 성능 개선을 위한 하이퍼파라미터 튜닝",
      challengeCount: 8,
      answerCount: 3,
      jobCategory: ["Data Science", "Machine Learning"],
      skills: ["Python", "Scikit-learn", "TensorFlow"],
    },
    {
      id: 45,
      status: "solved",
      questionContent: "TypeScript로 대규모 프로젝트 관리",
      challengeCount: 6,
      answerCount: 4,
      jobCategory: ["Frontend"],
      skills: ["TypeScript", "JavaScript", "React"],
    },
    {
      id: 46,
      status: "unsolved",
      questionContent: "Kotlin을 사용한 Android 앱 최적화",
      challengeCount: 3,
      answerCount: 1,
      jobCategory: ["Mobile"],
      skills: ["Kotlin", "Android", "Jetpack"],
    },
    {
      id: 47,
      status: "solved",
      questionContent: "Redis를 활용한 캐싱 전략",
      challengeCount: 4,
      answerCount: 3,
      jobCategory: ["Backend", "Database"],
      skills: ["Redis", "Node.js", "MongoDB"],
    },
    {
      id: 48,
      status: "unsolved",
      questionContent: "PostgreSQL과 MySQL의 성능 비교",
      challengeCount: 5,
      answerCount: 2,
      jobCategory: ["Database", "Backend"],
      skills: ["PostgreSQL", "MySQL", "SQL"],
    },
    {
      id: 49,
      status: "solved",
      questionContent: "Vue.js와 Nuxt.js를 활용한 SSR 구현",
      challengeCount: 6,
      answerCount: 5,
      jobCategory: ["Frontend"],
      skills: ["Vue", "Nuxt", "JavaScript"],
    },
    {
      id: 50,
      status: "unsolved",
      questionContent: "Elasticsearch를 활용한 로그 분석",
      challengeCount: 3,
      answerCount: 1,
      jobCategory: ["Database", "DevOps"],
      skills: ["Elasticsearch", "Logstash", "Kibana"],
    },
    {
      id: 51,
      status: "solved",
      questionContent: "GraphQL API 설계 패턴",
      challengeCount: 4,
      answerCount: 2,
      jobCategory: ["Backend", "Frontend"],
      skills: ["GraphQL", "Apollo", "Node.js"],
    },
    {
      id: 52,
      status: "unsolved",
      questionContent: "WebAssembly 성능 최적화",
      challengeCount: 5,
      answerCount: 3,
      jobCategory: ["Frontend"],
      skills: ["WebAssembly", "Rust", "C++"],
    },
    {
      id: 53,
      status: "solved",
      questionContent: "Unity 3D 게임 최적화",
      challengeCount: 7,
      answerCount: 4,
      jobCategory: ["Game Development"],
      skills: ["Unity", "C#", "3D Graphics"],
    },
    {
      id: 54,
      status: "unsolved",
      questionContent: "IoT 디바이스 보안",
      challengeCount: 3,
      answerCount: 1,
      jobCategory: ["Embedded", "Cyber Security"],
      skills: ["C", "IoT", "Encryption"],
    },
    {
      id: 55,
      status: "solved",
      questionContent: "스마트 컨트랙트 개발과 테스팅",
      challengeCount: 4,
      answerCount: 2,
      jobCategory: ["Blockchain"],
      skills: ["Solidity", "Ethereum", "Web3.js"],
    },
    {
      id: 56,
      status: "unsolved",
      questionContent: "마이크로프론트엔드 아키텍처",
      challengeCount: 6,
      answerCount: 3,
      jobCategory: ["Frontend"],
      skills: ["JavaScript", "Module Federation", "Webpack"],
    },
    {
      id: 57,
      status: "solved",
      questionContent: "자연어 처리를 위한 BERT 모델 활용",
      challengeCount: 5,
      answerCount: 2,
      jobCategory: ["Machine Learning"],
      skills: ["Python", "BERT", "TensorFlow"],
    },
    {
      id: 58,
      status: "unsolved",
      questionContent: "모바일 앱 자동화 테스트",
      challengeCount: 4,
      answerCount: 1,
      jobCategory: ["Mobile", "Testing"],
      skills: ["Appium", "Selenium", "Java"],
    },
    {
      id: 59,
      status: "solved",
      questionContent: "서버리스 아키텍처 구현",
      challengeCount: 3,
      answerCount: 4,
      jobCategory: ["Backend", "DevOps"],
      skills: ["AWS Lambda", "Serverless Framework"],
    },
    {
      id: 60,
      status: "unsolved",
      questionContent: "실시간 데이터 시각화",
      challengeCount: 5,
      answerCount: 2,
      jobCategory: ["Frontend", "Data Science"],
      skills: ["D3.js", "WebSocket", "React"],
    },
    {
      id: 61,
      status: "solved",
      questionContent: "임베디드 리눅스 커널 최적화",
      challengeCount: 6,
      answerCount: 3,
      jobCategory: ["Embedded"],
      skills: ["C", "Linux Kernel", "Assembly"],
    },
    {
      id: 62,
      status: "unsolved",
      questionContent: "풀스택 JAMstack 웹 개발",
      challengeCount: 4,
      answerCount: 1,
      jobCategory: ["Fullstack"],
      skills: ["Next.js", "Gatsby", "Headless CMS"],
    },
  ];
  
export default dummyQuestions;
  