spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
        debug: true
cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    s3:
      bucket-name: ${BUCKET}
    region:
      static: ${REGION}
    stack:
      auto: false
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.cors: DEBUG

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://${DEV_DATABASE_HOST}:5432/d3vdb
    driver-class-name: org.postgresql.Driver
    username: ${DEV_DATABASE_USER}
    password: ${DEV_DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}