spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  mail:
    host: smtp.gmail.com # ${MAIL_HOST}
    port: 587 # ${MAIL_PORT}
    username: by28287@gmail.com # ${MAIL_USERNAME}
    password: jtreizizqqjpurwu # ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
        debug: true
cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    s3:
      bucket-name: ${BUCKET}
    region:
      static: ${REGION}
    stack:
      auto: false
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.cors: DEBUG
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:dv3-local-db
    driver-class-name: org.h2.Driver
    username: user
    password:
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true # SQL 로그 출력
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    org.hibernate.SQL: debug # SQL 로그 출력을 위한 로그 레벨 조정



---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://${DEV_DATABASE_HOST}:5432/d3vdb
    driver-class-name: org.postgresql.Driver
    username: ${DEV_DATABASE_USER}
    password: ${DEV_DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: 52.78.105.9
      port: 6379